version: '3.3'
services:
  database:
    environment:
          - POSTGRES_USER=production
          - POSTGRES_PASSWORD=production
          - POSTGRES_DB=production
    ports:
      - '5432:5432'
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
      target: production
    ports:
      - '8080:8080'
