version: '3.3'
services:
  database:
    image: postgres:14.1
    volumes:
      - ./prepare_database.sql:/docker-entrypoint-initdb.d/prepare_database.sql

  backend:
    depends_on:
      - database
